-- Project: Retail Chain Sales Analytics Platform
-- Module: Security & Role-Based Access Control (RBAC)
-- Author: Shubhranshu Acharya


USE ROLE ACCOUNTADMIN;

-- Create Roles
CREATE OR REPLACE ROLE ANALYST_ROLE;
CREATE OR REPLACE ROLE MANAGER_ROLE;

-- Grant Warehouse Access
GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE RETAIL_WH TO ROLE MANAGER_ROLE;

-- Grant Database Access
GRANT USAGE ON DATABASE RETAIL_DW TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE RETAIL_DW TO ROLE MANAGER_ROLE;

-- Grant Schema Access
GRANT USAGE ON SCHEMA RETAIL_DW.RETAIL TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA RETAIL_DW.RETAIL TO ROLE MANAGER_ROLE;

-- Grant Table Privileges
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_DW.RETAIL TO ROLE ANALYST_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA RETAIL_DW.RETAIL TO ROLE MANAGER_ROLE;

-- Assign Roles to User
GRANT ROLE ANALYST_ROLE TO USER SHUBHRANSHU2026;
GRANT ROLE MANAGER_ROLE TO USER SHUBHRANSHU2026;

-- Create Masking Policy
CREATE OR REPLACE MASKING POLICY SALES_MASK_POLICY
AS (val NUMBER)
RETURNS NUMBER ->
    CASE
        WHEN CURRENT_ROLE() IN ('MANAGER_ROLE', 'ACCOUNTADMIN')
        THEN val
        ELSE NULL
    END;

-- Apply Masking Policy
ALTER TABLE RETAIL_DW.RETAIL.FACT_SALES
MODIFY COLUMN SALES
SET MASKING POLICY SALES_MASK_POLICY;